version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bilibili
